export { default as Header } from './Header';
export { default as Posts } from './Posts';
export { default as PostForm } from './PostForm';
export { default as Search } from './Search';
export { default as Footer } from './Footer';
export { default as MessageForm } from './MessageForm';
export { default as Messages } from './Messages';
export { default as MyPosts } from './MyPosts';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Home } from './Home';
export { default as Navbar } from './NavBar';
export { default as Profile } from './Profile';
export { default as LoginRegister } from './LoginRegister'
